name: PyTests

on: push

jobs:
  test:
    name: Run tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: |
          python -m tox -v